### ISSUE TITLE
"data" event gets emitted slowly (30ms) [Permormance]

### ISSUE THREAD

**Issue by flea89** [BareConductive/node-picap#1]
Diving in a little more I found that the bottleneck seems to be 
this.mpr121.step() that takes around 30ms to execute.

Same configuration in python is blazing fast 1-2 ms.

Shouldn't be comparable ? Shouldn't both of them using the same cpp module ?

Thanks

**Comment by stefandz** [comment]
Thanks for bringing this up - we've put it on our list of things to attend to and we should be able to get back to you next week. In the meanwhile if you have any further issues, please let us know.

**Comment by flea89** [comment]
thanks, really appreciated!

**Comment by stefandz** [comment]
Hi again. Have had a look at this and can see some performance lag, but not quite what you're describing. We've added an optional interval to the object initialisation (usage details in readme.md). I've also attached two benchmark files to this email - they output the average time for 1000 calls to `MPR121::updateAll()`.

[benchmarks.zip](https://github.com/BareConductive/node-picap/files/763959/benchmarks.zip)

The Python example is easy to run

    sudo python benchmark.py

The Node.js example is a little trickier

    nvm use 6.7.0
    npm install node-picap
    sudo $(which node) benchmark.js

Give these a whirl and let me know how you get on - I see about a 9ms speedup using the new `interval: 1` option in Node.js which brings its performance roughly inline with Python.

**Comment by flea89** [comment]
Thanks for checking this for me.
I just tried to run the benchmarks and I got 
node -> 0.041905905988004
python -> 0.0309171781645 (goes to 0.018245681778 removing the sleep).

The results are comparable, but from the benchmarks looks like both library are slower than I thought. 

Is that expected ?

Hardware:
piZero
Raspbian GNU/Linux 8.0 (jessie)

if that helps.

**Comment by szymonkaliski** [comment]
Hi @flea89, this results are comparable to ours, I think we should make similar cpp benchmark to establish baseline.

Out of curiosity, why would you need to receive data faster than every 0.03s?

**Comment by stefandz** [comment]
Is this still active? Going to close if there's no further interest.

**Comment by flea89** [comment]
I was just wondering since the hw sample rate of the picap was much higher .
Thanks for your help guys.
