### ISSUE TITLE
apt-get install picap "E: Unable to locate package picap"

### ISSUE THREAD

**Issue by mosspassion** [BareConductive/node-picap#2]
On a raspberry pi 2 I followed the instructions at ["Setting up your Pi Cap on the Raspberry pi 1, 2, or 3..."](https://www.bareconductive.com/make/setting-up-pi-cap-raspberry-pi/). But it would seem that your package is missing. I also did `apt-cache search picap` and it returned with zero results.

**Comment by loosepascal** [comment]
Hi Nicholas,

We'll have a look into it, in the meantime could you send us an email to info@bareconductive.com? Could you specify which version of Raspbian you are using?

Thank you!

Pascal

**Comment by nabeeh2010** [comment]
Hello, 

I am having the same issue as @mosspassion 

I'm unable to access the pi cap package.

Can you please help me resolve this?
