### ISSUE TITLE
Use without installing python packages?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [BareConductive/node-picap#3]
How do I use this without "apt-get install picap" and "picap-setup" ?

I can't install hundreds of python packages just to use this from node

**Comment by stefandz** [comment]
We deploy our code this way to make it easy for the majority of our users to get started where flash storage is relatively cheap (relative to solving issues for each user's particular configuration individually). This node module is just a wrapper for a C++ library, so if you want to install minimally you could clone our [wiringpi-mpr121](https://github.com/BareConductive/wiringpi-mpr121) repo and follow the instructions for build and install there. Once that's done, you can install node-picap via npm.

I would note that doing things this way means that you won't get any of the code examples (you'll have to search our repos for the examples you want from there) and you won't benefit from any library updates that are deployed via the Debian package system, so it will be up to you to keep an eye on code updates and manage these yourself.

I hope that helps - let me know how you get on.

**Comment by stefandz** [comment]
Hi - I am going to assume that this issue is now resolved. Please feel free to reopen if necessary.
