### ISSUE TITLE
"Unable to locate package picap"

### ISSUE THREAD

**Issue by nabeeh2010** [BareConductive/node-picap#4]
Hello @loosepascal,

I am having a similar issue as @mosspassion

When trying to install the picap package to my raspberry pi zero w, I'm getting a message that says "E: unable to locate package picap".

I've reached out to info@bareconductive.com, but have not heard back yet.

Can you please help me resolve this?

**Comment by loosepascal** [comment]
Hello,

I believed I have contacted you via info@bareconductive.com, is that correct?

**Comment by nabeeh2010** [comment]
Yes, that is correct. My issue is resolved.
